### ISSUE TITLE
FormBuilder Cleanup

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/ZoneMinder-tvOS#7]
Reviewing this repository, I see we have six different projects related to FormBuilder.  I'd like to review what we actually want from this.
- The AllowedTV form should probably be moved into the Cameras project as a second form.   Was there a reason why we wanted to keep these separate?  Having them separate means that we need to run through the Vagrant REST actions an extra time to get everything setup properly.
- Did you make any modifications to the JavaAgents or Royale projects?  If we don't need any modifications, we could exclude these projects and have the user regenerate them.  I have done this for other projects that use FormBuilder.

**Comment by rat-moonshine** [comment]
Cleanups:

- Included AllowedTVs form in CamerasAPI project
- Removed generated Java agent and Royale projects
